version: "3.8"

services:
  db:
    image: mysql:8
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtopia
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd